Signed-off-by: JiangYu <lnsyyj@hotmail.com> bootstrap Add CentOS Linux release 7.3.1611 support

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -54,6 +54,25 @@ Linux)
             fi
 	fi
 	;;
+    CentOS)
+        for package in python2-pip python-virtualenv mariadb-devel libev-devel libvirt-devel libffi-devel; do
+        if [ "$(rpm -q $package)" == "package $package is not installed" ]; then
+        missing="${missing:+$missing }$package"
+        fi
+        done
+    if [ -n "$missing" ]; then
+            echo "$0: missing required packages:" 1>&2
+            echo "$missing"
+            if [ "$install" = true ]; then
+                echo "Installing missing packages..."
+                sudo yum -y install $missing
+            else
+                echo "Please install missing packages or run './bootstrap install' if you have sudo"
+                echo "sudo yum -y install $missing"
+                exit 1
+            fi
+    fi
+    ;;
     Fedora)
         for package in python-pip python-virtualenv libev-devel libvirt-devel community-mysql-devel libffi-devel; do
 	    if [ "$(rpm -q $package)" == "package $package is not installed" ]; then
